SuperViz/sdk

- src/services/realtime/ably/index.ts
fix: don't replace avatarUrl if its undefined
> fix: don't replace avatarUrl if its undefined

- .gitignore
- src/common/types/sdk-options.types.ts
- src/services/remote-config-service/index.ts
With this feature, the user can get the remoteConfig (apikey and conferenceLayerUrl) locally.
for use this, the user need to create a .remote-config.js file in root directory with this content:
```
export const remoteConfig = {
apiUrl: 'https://localhost:4000', //your api url
conferenceLayerUrl: 'https://localhost:8080', //your video-frame url
}
```
and set the `environment: 'local'` in SDK initialization.
> fix: added local configuration file 

- src/index.ts
- src/services/realtime/ably/index.ts
The channel names were confusing and difficult to distinguish between them, so I think it could be simpler
> fix: realtime channel names

- src/common/types/events.types.ts
- src/services/communicator/index.ts
- src/services/communicator/types.ts
- src/services/video-conference-manager/index.ts
Users can create transcripts of their meetings, which is very useful for later analysis and especially searching for keywords or specific contexts. You need to choose language on start the transcription, the default language is `en-US`.
```
// Default language is en-US
sdk.startTranscription(language: string) => Promise<void>
sdk.stopTranscription() => Promise<void>
```
Users can use Start and Stop functions to control the transcription, we recommend only host can control the transcription service.
Example:
```
// start the meeting with pt-BR language
sdk.startTranscription('pt-BR')
```
```
// stop the meeting
sdk.stopTranscription()
```
> feat: added support to transcription service

- src/services/video-conference-manager/index.ts
`FrameEvent.FRAME_PARENT_SIZE_UPDATE` was not considering the offset when sending the size of the parent
---
> fix: calc parent dimensions considering offset

- src/common/types/events.types.ts
- src/index.test.ts
- src/services/communicator/ index.test.ts
- src/services/communicator/index.ts
- src/services/communicator/types.ts
- src/services/realtime/ably/index.test.ts
- src/services/realtime/ably/index.ts
- src/services/realtime/ably/types.ts
- src/services/video-conference-manager/index.test.ts
- src/services/video-conference-manager/index.ts
This update internal events from sdk to video-frame in transcript feature, this allows to share the transcript state from participants and change the layout like toolbar and alerts for notify the participants about transcription running.
> fix: change the transcript events to send message to video-frame

- src/common/utils/do-request.test.ts
- src/common/utils/do-request.ts
- src/components/base/index.test.ts
- src/components/base/index.ts
- src/components/video/index.ts
- src/core/index.test.ts
- src/core/launcher/index.test.ts
- src/core/launcher/index.ts
- src/services/api/index.test.ts
- src/services/api/index.ts
With this feature it is possible to create an analytical dashboard, with Components usage. Can be filtered by participant, groupId or meetingId.
> feat: create function to send the activity of participant to api

- src/components/video/index.test.ts
- src/components/video/index.ts
- src/components/video/types.ts
- src/services/video-conference-manager/index.ts
This PR changes the `MEETING_PARTICIPANT_LIST_UPDATE` and `MEETING_PARTICIPANT_AMOUNT_UPDATE` events logic, previously this list was the real-time attendee list, now it is updated by meeting attendees.
> feat: update participant list from meeting service

- __mocks__/realtime.mock.ts
- src/components/video/index.test.ts
- src/components/video/index.ts
Implements recursion to wait to join the realtime room. It's necessary because videoconferencing depends on the realtime room state and realtime participants to initialize the meeting room.
> fix: wait user enter realtime to initialize video

- lib.md
- src/common/types/cdn.types.ts
- src/common/utils/index.ts
- src/common/utils/observable.test.ts
- src/common/utils/observable.ts
- src/components/base/index.test.ts
- src/components/base/index.ts
- src/components/index.ts
- src/components/realtime/index.test.ts
- src/components/realtime/index.ts
- src/components/types.ts
- src/core/launcher/index.test.ts
- src/core/launcher/index.ts
- src/core/launcher/types.ts
- src/index.ts
- src/services/pubsub/index.test.ts
- src/services/pubsub/index.ts
- src/services/realtime/ably/index.ts
Before: 
```ts
const SuperViz = await Manager(DEVELOPER_KEY, {
roomId: this.roomId,
participant: {
id: this.userId,
name: 'John Doe',
type: userType,
avatar: {
thumbnail: 'https://production.storage.superviz.com/readyplayerme/1.png',
},
},
});
// PubSub
SuperViz.unsubscribe('presence-updated', () => {});
SuperViz.subscribe('presence-updated', () => {});
SuperViz.publish('presence-updated', {});
```
After: 
```ts
const SuperViz = await Manager(DEVELOPER_KEY, {
roomId: this.roomId,
participant: {
id: this.userId,
name: 'John Doe',
type: userType,
avatar: {
thumbnail: 'https://production.storage.superviz.com/readyplayerme/1.png',
},
},
});
const realtime = new Realtime();
SuperViz.addComponent(realtime);
// PubSub
realtime.unsubscribe('presence-updated', () => {}); …
```
> feat: realtime component

- src/web-components/comments/comments.ts
- src/web-components/comments/components/annotation-resolved.ts
- src/web-components/comments/components/comment-item.test.ts
- src/web-components/comments/components/comment-item.ts
- src/web-components/comments/components/content.test.ts
- src/web-components/comments/components/content.ts
- src/web-components/comments/css/comment-item.style.ts
Standardizes the size of the button of resolving comments and the one that opens a dropdown with "Edit" and "Delete" as options. Also gives more spacing between them.
Also, when a comment is selected, the container scrolls to show it.
> feat: size buttons and scroll selected

- src/services/limits/index.ts
- src/services/realtime/ably/index.ts
- src/web-components/comments/utils/watermark.ts
Previously, the host would update the event backup and it worked great, but when we changed the host logic to only work as video, this backup logic stopped working. To fix this, the attendee needs to update the event list with their events.
> fix: realtime history backup

- src/components/comments/index.ts
Comments were being deleted from canvas, but not from the sidebar. Add call to updateAnnotationList inside deleteComment to achieve the desired behavior
> fix: update annotations when deleting comments

- src/components/comments/canvas-pin-adapter/index.test.ts
- src/components/comments/canvas-pin-adapter/index.ts
- src/components/comments/index.ts
- src/web-components/comments/components/annotation-item.ts
- src/web-components/comments/components/annotations.ts
- src/web-components/comments/components/comment-input.ts
- src/web-components/comments/components/comment-item.ts
- src/web-components/comments/components/content.ts
- When writing an annotation/comments, pressing "Enter" in the keyboard emits the event to create it
- Clicking twice on a pin/comment toggles its "selected"/"active" attribute
- Pressing "Esc" cancels a few things, such as the "selected"/"active" attribute of an annotation, or the creation of a new annotation
> feat: react to keyboard mouse events

- src/common/types/cdn.types.ts
- src/components/realtime/index.test.ts
- src/components/realtime/index.ts
- src/components/realtime/types.ts
- src/index.ts
Adds support to subscribe callbacks before initialization of the realtime, and publishes a message to the client whenever the state of the component changes. For now, we only have STARTED and STOPPED.
> feat: add event to realtime start/stop

- __mocks__/participants.mock.ts
- src/components/who-is-online/index.test.ts
- src/components/who-is-online/index.ts
With these changes, the only prerequisite to use Who Is Online will be activating the component itself, instead of depending on the participant also activating Presence. Thanks to that change, a good chunk of code was removed due to contrived or out of date logic, and a few changes were made to the already existing method of updating the participants list.
> feat: make wio independent from presence

- src/web-components/who-is-online/components/dropdown.ts
- src/web-components/who-is-online/css/dropdown.style.ts
> fix: display extra participants avatars with correct proportions

- .github/workflows/ci.yml
For this PR to be merged it will need the PAT (Personal Access Token) for SuperViz-Dev with access to GitHub Actions as a Secret named token: `GITHUB_SUPERVIZ_DEV_USER_TOKEN `
> ci: update secret name for ci

- src/components/comments/html-pin-adapter/index.test.ts
- src/components/comments/html-pin-adapter/index.ts
- src/components/comments/html-pin-adapter/types.ts
- src/components/who-is-online/index.ts
- src/web-components/who-is-online/components/dropdown.ts
- src/web-components/who-is-online/components/types.ts
- src/web-components/who-is-online/css/who-is-online-style.ts
- src/web-components/who-is-online/who-is-online.ts
Now, if either local participant or another participant is not in Presence, do not show 'Click to Follow' when hovering over other participant avatar. Besides, the mouse pointers of other participants in Presence do not show over WIO avatars and dropdown anymore.
> fix: wio interaction with presence

- src/components/comments/canvas-pin-adapter/index.test.ts
- src/components/comments/canvas-pin-adapter/index.ts
Use CSS to render our mouse cursor, instead of creating a HTML element to do this
As a bonus, when closing the sidebar, the temporary pin now disappears and any selected pin is unselected. I could swear this already happened, but empirical observations proved that that was not the case
> feat: render cursor with css

- src/components/comments/canvas-pin-adapter/index.ts
- src/components/comments/html-pin-adapter/index.test.ts
- src/components/comments/html-pin-adapter/index.ts
- src/components/comments/index.ts
In Comments, both with CanvasPin and HTMLPin:
- If creating an annotation and then clicking on another part of the screen (say, for example, in the comments sidebar), hide temporary pin and input
- Do not do anything at all when participant creates an annotation. No sort of translation, nor anything
> feat: hide temp pin click

- src/components/comments/html-pin-adapter/index.ts
Change in the logic of how pins are positioned on the screen and appended in the DOM when creating an annotation over a rect or ellipse to account for when the user scrolls
> fix: position pin correctly on scroll

- src/common/types/events.types.ts
- src/components/comments/index.test.ts
- src/components/comments/index.ts
- src/components/comments/types.ts
- src/web-components/comments/comments.ts
- src/web-components/comments/components/topbar.ts
- src/web-components/comments/css/topbar.style.ts
Instead of relying purely on our button to handle the state of comments, we now allow the user to invoke methods that opens or closes the comments threads/sidebar, as well as methods that allow add new pins to the elements or not. Our button, now, only toggles the active/inactive status of the pins (that is, if the user can add or not new pins), and there's now even a flag to hide the button.
https://github.com/SuperViz/sdk/assets/111044527/95ee8002-8ed0-46ca-b528-4d6d534781ac
> feat: comments v3

- src/web-components/comments/components/mention-list.test.ts
- src/web-components/comments/components/mention-list.ts
When utilizing external events for zoom and mouse movements, the list of mentions fails to scroll.
Resolved issue with participant list scrolling despite external events.
> Fix: mentions dropdown list with scroll

- src/web-components/comments/components/annotation-filter.ts
- src/web-components/comments/components/annotation-pin.ts
- src/web-components/comments/components/comment-input.ts
- src/web-components/comments/components/comment-item.ts
- src/web-components/comments/components/float-button.ts
- src/web-components/comments/components/topbar.ts
- src/web-components/dropdown/index.ts
- src/web-components/icon/index.ts
- src/web-components/modal/modal-container.test.ts
- src/web-components/modal/modal-container.ts
- src/web-components/who-is-online/components/dropdown.ts
- src/web-components/who-is-online/css/dropdown.style.ts
Remove flag allowSetSize from <superviz-icon>
In the past, it was added to buy time, since a few changes made in the component meant that all the icons that we use could potentially break, appearing larger or smaller than they should be. Since reviewing this was not a priority, adding this flag was a simple, quicky, dirty solution
> fix: remove allowSetSize property from superviz-icon component

- src/components/comments/html-pin-adapter/index.test.ts
Create some tests for the main method responsible for handling svg elements with the Comments HTML Pin. 
This wasn't done before because I thought of the compatibility with svg elements in the HTML Pin as only an afterthought, with the possibility of svg elements getting their own pin adapter, so the HTML Pin wouldn't need to handle it. But hey, it doesn't seem that the need for some svg compatibility is going away soon, so why not test it?
> feat: tests svg html pin

- src/components/presence-mouse/html/index.ts
Take scale of element the mouse is into in consideration when moving it
> fix: mouse behavior on html when scale is different from 1

- src/common/types/stores.types.ts
- src/common/utils/use-store.ts
- src/components/presence-mouse/html/index.ts
- src/components/who-is-online/index.ts
- src/components/who-is-online/types.ts
- src/services/stores/who-is-online/index.ts
- src/web-components/who-is-online/components/dropdown.test.ts
- src/web-components/who-is-online/components/dropdown.ts
- src/web-components/who-is-online/who-is-online.ts
- Update mouse positions immediately after using transform on them, instead of waiting for next participant interaction
- Change what coordinates exactly the HTML mouse component calls the user callback with in goToPresence (Before: Coordinates relative to the user viewport. Now: Coordinates relative to the container)
- Create flag for disabling presence controls in WIO even when using it with presence
> feat: mouse follow and wio flag

- src/web-components/comments/components/comment-input.ts
- src/web-components/comments/components/comment-item.ts
This commit addresses the issue where entering editing mode did not properly focus on the content being edited and did not make the send button available. Now, when users enter editing mode, the cursor is properly placed within the editing field, and the send button is visible for sending the edited content. This improves the user experience and ensures smooth interaction with the editing feature.
- **fix: ensure focus and send button in editing mode**
> fix: reply input

- src/components/realtime/index.test.ts
- src/components/realtime/index.ts
- src/components/who-is-online/index.ts
- src/core/launcher/index.ts
Fixed a bug that occurred when trying to get the room history before the component started. Now it skips the history fetch, returns null to the client, and logs a warning to the console explaining what happened. 
When a participant joins the room, if the room has other participants who joined before him, the SDK was emitting participant joined event to them too. To fix this, we get the attendee list from the IO when the SDK is started 
We just keep it on the old IO until we migrate all the components to the new IO. It prevents bugs and weird behavior
> Participant events with new IO

- jest.setup.js
- package.json
- src/components/presence-mouse/canvas/index.test.ts
- src/components/presence-mouse/canvas/index.ts
- src/components/presence-mouse/html/index.test.ts
- src/components/presence-mouse/html/index.ts
- src/components/presence-mouse/types.ts
- yarn.lock
Implementing a simple camera to see what the participants are seeing all the time. 
The coordinates that the `follow' functionality is based on have also been changed, before we centralized the mouse of the participant being followed, now we just centralize the view of the participant and calculate the scale that allows the mouse of the participant being followed to be seen at all times by the participant being followed. 
So the `onGoToPresence` callback has been changed to add the scale x and y factors. And also the `transform` method has been deprecated in the canvas mouse pointers, it's no longer necessary, we calculate all coordinates internally. 
- Change camera example: 
```ts
let cameraZoom = 0;
const cameraOffset = { x: 0, y: 0 };
const mousePointers = new …
```
> feat: sync the current translate and scale in the presence mouses

- __mocks__/config.mock.ts
- src/components/base/index.ts
- src/core/index.ts
- src/core/launcher/index.ts
- src/services/config/index.ts
- src/services/config/types.ts
- src/services/remote-config-service/index.ts
- src/services/remote-config-service/types.ts
- src/services/video-conference-manager/index.ts
- src/services/video-conference-manager/types.ts
Introducing feature flags to SDK. Adding service to enable/disable features by apiKey.
> feat: feature flags

- package.json
- src/components/realtime/channel.test.ts
- src/components/realtime/channel.ts
- src/components/realtime/index.test.ts
- src/components/realtime/index.ts
- src/components/realtime/types.ts
- yarn.lock
Implementing Multi-Channel Support
Previously, only supported a single channel. Now, I'm introducing multi-channel support, allowing clients to define their own channels.
Now, I've implemented multi-channel support, enabling clients to define their own channels. To achieve this, I've created a new class capable of distributing methods for `subscribe`, `unsubscribe`, `publish`, and `disconnect`.
Previously, when connecting to Realtime, we would receive one channel along with its respective handling methods.
```ts
const realtime = Realtime()
realtime.subscribe()
realtime.publish()
realtime.fetchHistory()
```
Now, with the introduction of multi-channel support, we instantiate the Realtime class and then connect to whichever channels are desired. For example:
```ts
const realtime = Realtime() …
```
> feat: add support to multi channels

- src/components/base/index.ts
- src/components/video/index.ts
Fixed a bug that didn't destroy the video frame when the participant leaves the meeting. 
**Explanation**: Sometimes the process to destroy the video took too long, it's cause the video services lost the frame reference, causing an error that made it impossible to get destroyed. 
**To solve**: We make sure that the first thing we do when the participant leaves the meeting room is to destroy the frame. This will prevent the error and ensure that the meeting overlay is destroyed.
> fix: ensure that video frame is destroyed

- src/common/types/stores.types.ts
- src/components/base/index.test.ts
- src/components/base/types.ts
- src/components/comments/index.test.ts
- src/components/form-elements/index.test.ts
- src/components/presence-mouse/canvas/index.test.ts
- src/components/presence-mouse/html/index.test.ts
- src/components/realtime/index.test.ts
- src/components/video/index.test.ts
- src/components/who-is-online/index.test.ts
- src/core/launcher/index.ts
An error was happening while trying to use the previous lab version from sdk in the 3d plugins. Both the StoreType enum and the Presence3dManager class needed to be imported from the SDK, but this meant generating conflicts because the web-components were redefined and all that. 
By passing the class through the params so the plugins could create new instances of the Presence 3D Manager without importing anything, and by making sure that the Stores would work even without using any enums, these problems are solved.
> fix: make features acessible to 3d without importing from sdk

- src/components/video/index.ts
- Invert the order of host selection based on timestamp. Now, correctly take as host the one with the lowest timestamp (thus, the older in the room)
- Delete from the list of potential hosts those who leave the room
- Only call the method that sets hosts for the first time after ensuring that the list with participants and their types is set
> fix: correct host order

- src/components/video/index.test.ts
- src/components/video/index.ts
In some rare cases, it was trying to validate and set hosts even before confirming which types other participants are, leading to a new participant being assigned as the host even if there already was a host in the room. Setting a flag right after processing the list and then early returning if the flag is still false seems to be the most direct and failproof way of ensuring the host is only set at the right time
> fix: make sure that hosts are only validated after list is initialized

- src/components/base/index.test.ts
- src/components/base/index.ts
- src/components/base/types.ts
- src/components/comments/index.test.ts
- src/components/form-elements/index.test.ts
- src/components/presence-mouse/canvas/index.test.ts
- src/components/presence-mouse/html/index.test.ts
- src/components/realtime/index.test.ts
- src/components/video/index.test.ts
- src/components/video/index.ts
- src/components/who-is-online/index.test.ts
- src/core/launcher/index.ts
- src/services/roomState/index.test.ts
- src/services/roomState/index.ts
Fix the bug that made participants joining a room not properly set the room properties for themselves (For example: in a room where transcript is on, new participants would join the room with transcript off).
There were two problems: 
- Instead of getting the most recent event in the room, it was getting the oldest. 
- The room state service was starting to soon and trying to set the room properties even before the frame initialized. 
The fix for the first problem was changing `events[0]` to `events.pop()`
The fix for the second problem was only instantiating the service after receiving the confirmation that the frame was initialized. Right after that, it tries to fetch the room properties, instead of waiting for the participant joined room event. The participant already joined the room …
> fix: properly fetch room state

- src/core/launcher/index.ts
- src/services/slot/index.test.ts
- src/services/slot/index.ts
It ensures that any changes made to the slots will update the global store and the default real-time room.
> fix: slot assignment dont syncing in the stores

- src/components/realtime/channel.ts
- src/components/realtime/index.ts
Add a default channel to handle the messages if the client don´t want to create channels.
> feat: add a default channel to realtime component

- src/common/types/stores.types.ts
- src/components/video/index.test.ts
- src/components/who-is-online/index.test.ts
- src/core/launcher/index.test.ts
- src/services/stores/presence3D/index.ts
- src/services/stores/subject/index.test.ts
- src/services/stores/subject/index.ts
- src/services/stores/who-is-online/index.ts
- Identify and store multiple subscriptions to the same subject in a store using the same `subscriptionId`
- Restart the subject to its initial state after it is destroyed in case the room starts again
> fix: properly unsubscribe from subject that was subscribed to twice

- package.json
- src/components/realtime/channel.ts
- src/components/realtime/types.ts
- src/core/index.ts
- yarn.lock
After that, the SDK will be able to receive messages sent by HTTP real-time endpoint 🎉. 
- Updates the socket client version 
- Prepare **realtime channels** and `realtimeMessage` to receive messages without participants
> feat: recieves messages sended by http method

- src/components/video/index.ts
- src/core/launcher/index.ts
- src/services/stores/global/index.ts
When destroying a room with video, I noticed some errors on the console
Publishing to the stores the localParticipant as undefined was bound to throw some error, since no subscription to the global store was made with the possibility of the local participant being undefined in mind
When destroying the video, the Video Manager was being destroyed before the Video component tried to unsubscribe from the Observers in the VM, so an error was thrown
> fix: errors on destroy room

- .esbuild/build.js
- .esbuild/config.js
- .esbuild/watch.js
- package.json
- Implemented support for ES Modules (ESM) as entry points in the build configuration.
- Configured the build process to output files in ESM format and CJS Format
- Enabled code splitting to generate separate chunks, optimizing load times and improving performance.
> fix: add suport to ESM entrypoint and build it in separated chunks

- __mocks__/participants.mock.ts
- src/common/types/participant.types.ts
- src/components/presence-mouse/canvas/index.ts
- src/components/presence-mouse/html/index.ts
- src/components/video/index.test.ts
- src/components/video/index.ts
- src/components/video/types.ts
- src/core/launcher/index.test.ts
- src/core/launcher/index.ts
- src/services/slot/index.test.ts
- src/services/slot/index.ts
- src/web-components/who-is-online/components/messages.ts
Previously, when a user entered the room, we would assign them a slot, now we only assign slots to users who need a slot. 
Example: If a user is in real-time, they don't need a slot because it's not a slot for anything. But if a user is in WIO, they will need a slot because it's used to show what colour that user has. 
To improve this logic, we observe the user list in the store, find what's component is active in this time, when has a component that need slot, we assign a slot to user. If it doesn't, we assign the default slot to the user, in this case the grey slot. 
--- 
There is also an edge case, users that are only in video and the type is `audience` shouldn't have a slot too.
> Improve slot assignment and de-assignment

- __mocks__/limits.mock.ts
- src/components/base/index.test.ts
- src/components/base/index.ts
- src/components/base/types.ts
- src/components/comments/index.test.ts
- src/components/form-elements/index.test.ts
- src/components/presence-mouse/canvas/index.test.ts
- src/components/presence-mouse/html/index.test.ts
- src/components/realtime/channel.test.ts
- src/components/realtime/channel.ts
- src/components/realtime/index.test.ts
- src/components/realtime/index.ts
- src/components/types.ts
- src/components/video/index.test.ts
- src/components/who-is-online/index.test.ts
- src/core/index.ts
- src/core/launcher/index.test.ts
- src/core/launcher/index.ts
- src/services/io/index.ts
- src/services/limits/index.test.ts
- src/services/limits/index.ts
- src/services/limits/types.ts
- src/services/slot/index.test.ts
- src/services/slot/index.ts
Before that, all the components have the same limit because it's implemented by room, it means all the components follow the maximum connections implemented by room, in this case it was 16 because it was the total slot count. 
After that, the component has the limits by itself, it means we have components that can have more connections and component that can have less connections in the same room. 
Example: if the client is using comments with video, they can connect 255 participants (between audience and guest/host) in the video room, but in the comments room they can only connect 50 participants. 
It will allow more possibilities to the components because they will no longer be limited by the room.
To know what limits we have, and the price, visit: https://www.superviz.com/pricing
> Implement connection limits by product instead of by room

- .esbuild/config.js
In the previous version we improved the build by adding separated files to ESM and CJS. 
But specifically with next js older versions, we have a problem with minify. 
To solve this problem, we add a fixed target to our esm config.
> fix: add target to esm build

- package.json
- src/components/video/index.ts
- src/core/launcher/index.ts
- yarn.lock
Fixed a small bug where if the video component was destroyed internally, the component wasn't removed from the `activeComponents` list, preventing the client from adding the component again.
> fix: internal video destroys don't remove component from activeComponents list

- src/core/launcher/index.ts
- src/services/io/index.ts
Making sure the `activeComponents` list is updated and not duplicated, and making sure we're saving the right component instances to destroy when the room is destroyed.
I also noticed that the IOC was forcing a reconnect when the room was destroyed, this was also fixed.
> fix: active components lists

- jest.config.js
- package.json
- src/core/index.ts
- src/lib/socket/connection/index.ts
- src/lib/socket/presence/index.ts
- src/lib/socket/room/index.ts
- src/services/api/index.test.ts
- src/services/api/index.ts
- src/services/roomState/index.ts
- yarn.lock
Adding request to load the products limits by server.
> feat: load limits from server

- src/core/index.test.ts
- src/core/index.ts
Adding validations to ensure the users is following the room id and participant id rules. 
New rules: 
- Length Constraints: Minimum length of 2. Maximum length of 64.
- Pattern: `[-_&@+=,(){}\[\]\/«».:|'"#a-zA-Z0-9À-ÿ\s]*`
New message errors: 
Room ID invalid
```
[SuperViz] Room id is invalid, it should be between 2 and 64 characters and only accept letters, numbers and special characters: -_&@+=,(){}[]/«».:|\'"
```
Participant ID invalid: 
```
[SuperViz] Participant id is invalid, it should be between 2 and 64 characters and only accept letters, numbers and special characters: -_&@+=,(){}[]/«».:|\'"
```
> feat(core): validate if the user id and room id follow the right pattern

- src/core/launcher/index.test.ts
- src/core/launcher/index.ts
- src/services/io/index.ts
Before, we update the active instances every time the local subscriber is updated in the store, but we have a lot of updates in the store, every time the subscriber is updated. 
So, to improve this flow and prevent problems, we're going to update the active instances only when the customer adds and removes a component, to prevent duplication, we're going to validate and replace the instance when it's necessary.
> fix: only update active instances when a component is added or removed
