SuperViz/sdk

src/services/communicator/index.ts, src/services/integration/base-adapter/index.ts, src/services/integration/base-adapter/types.ts, src/services/realtime/ably/index.ts, src/services/realtime/ably/types.ts
remove old slot types and use another approach
=> fix: slot system

src/services/realtime/ably/index.ts
=> fix: getUserSlot

src/services/communicator/index.ts, src/services/realtime/ably/index.ts
fix: update actors list as much as possible
=> fix: update actors list as much as possible

src/services/communicator/index.ts, src/services/integration/index.ts, src/services/realtime/ably/index.ts
chore: move first avatarUpdate
=> chore: move first avatarUpdate

src/services/communicator/index.ts, src/services/communicator/types.ts, src/services/integration/base-adapter/types.ts, src/services/integration/index.ts, src/services/realtime/base/index.ts
=> feat: disconnect adapter

src/services/communicator/index.ts, src/services/communicator/types.ts, src/services/integration/base-adapter/index.ts, src/services/integration/base-adapter/types.ts, src/services/integration/index.ts, src/services/integration/types.ts, src/services/integration/users/index.ts, src/services/integration/users/types.ts
feat: add avatar scale and height to options
=> feat: add avatar scale and height to options

src/services/communicator/index.ts, src/services/integration/users/index.ts
fix scale and height adjust of avatars
=> fix: scale and height adjust

src/services/realtime/ably/index.ts
=> fix slot system

src/services/integration/index.ts
=> fix: add missing parameters and add logs for testing

src/services/communicator/index.ts, src/services/integration/index.ts, src/services/realtime/ably/index.ts
=> fix: presence update avatars was breaking if updated too early

.esbuild/build.js, src/services/integration/index.ts
=> chore: add logs to debug

.esbuild/build.js, src/services/communicator/index.ts, src/services/integration/index.ts
fix: avatar creation because getting actor list to early
=> fix: avatar creation

src/services/integration/index.ts, src/services/realtime/ably/index.ts
* send a sync when someone enters
* fix adapter function call for gather
=> feat: send a sync when someone enters + fix function call

src/services/communicator/index.ts, src/services/integration/base-adapter/index.ts, src/services/integration/base-adapter/types.ts, src/services/integration/index.ts, src/services/integration/users/types.ts
Only merge when we update the adapters
=> feat: add showName avatar config + getAvatars interface

.esbuild/config.js, __mocks__/event-bus.mock.ts, package.json, src/components/base/index.test.ts, src/components/base/index.ts, src/components/base/types.ts, src/components/video/index.test.ts, src/core/launcher/index.test.ts, src/core/launcher/index.ts, src/services/event-bus/index.test.ts, src/services/event-bus/index.ts, yarn.lock
* Add service to send and listen events between components. 
* Add loader to style and font files.
=> feat: add event bus to internal events between components

src/components/video/index.test.ts, src/components/video/index.ts
* Send go to event to 3D components using event bus.
=> feat: publish go to event from video component

src/web-components/base/index.test.ts, src/web-components/base/index.ts, src/web-components/icon/index.test.ts, src/web-components/icon/index.ts, src/web-components/index.ts, web-test-runner.config.js
This pull request implement inject styles in to shadowRoot, and add a web component to handle superviz icon library.
=> feat: icon component

__mocks__/realtime.mock.ts, src/components/base/index.test.ts, src/components/base/index.ts, src/components/comments/index.test.ts, src/components/comments/index.ts, src/components/video/index.test.ts, src/components/video/index.ts, src/services/realtime/ably/index.ts, src/services/realtime/base/index.ts
Add support to real-time sync into annotations 🚀
=> feat: comments sync

.esbuild/config.js, .husky/pre-commit, __mocks__/realtime.mock.ts, package.json, src/common/types/events.types.ts, src/core/launcher/index.ts, src/services/pubsub/index.ts, src/services/realtime/ably/index.ts, src/services/realtime/ably/types.ts, src/services/realtime/base/index.ts, tsconfig.json, yarn.lock
- Merge branch 'beta' of github.com:SuperViz/sdk into lab
- chore(build-config): change outdir to lib
=> main to lab

.remote-config.js, __mocks__/config.mock.ts, __mocks__/limits.mock.ts, src/components/base/index.test.ts, src/components/base/index.ts, src/components/presence-mouse/index.ts, src/components/types.ts, src/components/video/index.ts, src/core/index.ts, src/core/launcher/index.test.ts, src/core/launcher/index.ts, src/services/api/index.test.ts, src/services/api/index.ts, src/services/config/types.ts, src/services/limits/index.test.ts, src/services/limits/index.ts, src/services/limits/types.ts
With this new LimitsService, the user can check if you limit has reached and cant add a component in sdk
=> feat: create service for check the usage of users

.github/workflows/ci.yml
Changing build directory to fix that action:
=> ci: change build directory from dist to lib

__mocks__/comments.mock.ts, src/components/comments/index.test.ts, src/components/comments/index.ts, src/web-components/comments/comments.test.ts, src/web-components/comments/comments.ts, src/web-components/comments/css/index.test.ts, src/web-components/comments/css/index.ts, src/web-components/comments/css/powered-by.style.ts, src/web-components/comments/utils/watermark.test.ts, src/web-components/comments/utils/watermark.ts
feat add watermark to sdk comments 
and add observer to load or reload footer
=> feat: add watermark to sdk comments

src/components/presence-mouse/index.test.ts, src/components/presence-mouse/index.ts, src/web-components/presence-mouse/index.ts
The mouse pointer is not shown on selected element id
=> fix: mouse pointer is not shown

src/common/types/cdn.types.ts, src/components/video/index.ts, src/components/video/types.ts, src/index.ts, src/services/video-conference-manager/index.ts, src/services/video-conference-manager/types.ts
Provides a flag to set the initial layout for cameras in video calls
=> feat: add layout mode flag

__mocks__/comments.mock.ts, src/common/types/participant.types.ts, src/components/comments/index.test.ts, src/components/comments/index.ts, src/components/comments/types.ts, src/core/launcher/index.ts, src/services/api/index.ts, src/web-components/comments/components/annotation-item.ts, src/web-components/comments/components/annotation-pin.ts, src/web-components/comments/components/comment-item.test.ts, src/web-components/comments/components/comment-item.ts, src/web-components/comments/css/comment-item.style.ts
Adding user name and avatar to comments 🥳
=> feat: add username and avatar to comments

__mocks__/realtime.mock.ts, src/common/types/participant.types.ts, src/common/types/sdk-options.types.ts, src/components/video/index.test.ts, src/components/video/index.ts, src/components/video/types.ts, src/core/launcher/index.test.ts, src/core/launcher/index.ts, src/core/launcher/types.ts, src/services/realtime/ably/index.test.ts, src/services/realtime/ably/index.ts, src/services/realtime/base/types.ts
add validations to add/remove components based on acvite component list
remove shouldKickParticipants from laucher and add allowGuests do video-component
=> feat: allow guests 

src/core/launcher/index.ts
Fix active components when initialize a component on SDK
=> Fix: active components when initialize a component

src/components/comments/index.ts, src/web-components/comments/components/float-button.ts, src/web-components/comments/components/topbar.test.ts, src/web-components/comments/components/topbar.ts, src/web-components/comments/css/comments.style.ts, src/web-components/comments/css/float-button.style.ts, src/web-components/comments/css/topbar.style.ts
=> feat: change comments side

.github/workflows/checks.yml, .github/workflows/ci.yml, .remote-config.js, jest.setup.js, lib.md, src/common/types/sdk-options.types.ts, src/components/video/index.test.ts, src/components/video/index.ts, src/components/video/types.ts, src/core/index.ts, src/core/launcher/index.test.ts, src/core/launcher/index.ts, src/services/realtime/ably/index.test.ts, src/services/realtime/ably/index.ts, src/services/remote-config-service/index.ts
* Set host participant type only to participants on video component, and add option into VideoComponent to set `UserType`
* Remove remote-config file and fix ci and checks workflows
* Add new `collaborationMode` flag into video component to change the video layout.
=> feat: set host participant level only to participants on video component

__mocks__/config.mock.ts, __mocks__/watermark.mock.ts, src/components/comments/index.test.ts, src/components/comments/index.ts, src/components/video/index.test.ts, src/components/video/index.ts, src/core/index.ts, src/services/api/index.test.ts, src/services/config/types.ts, src/services/limits/index.test.ts, src/services/limits/index.ts, src/services/video-conference-manager/index.ts, src/services/video-conference-manager/types.ts
The watermark is not shown on free plan.
The fix resolve the bug to video and comments components.
=> fix: show watermark on free plan

package.json, src/components/comments/canvas-pin-adapter/index.test.ts, src/components/comments/canvas-pin-adapter/index.ts, src/components/comments/index.test.ts, src/components/comments/index.ts, src/components/comments/types.ts, yarn.lock
- chore(deps): bump sv-icons version
- fix: don't send query params to comments
- feat: annotation pins is always visibles
=> feat: pins is always visibles

__mocks__/limits.mock.ts, src/components/comments/canvas-pin-adapter/index.ts, src/components/types.ts, src/services/limits/types.ts, src/web-components/comments/components/annotation-pin.ts
- fix: product names
- fix: add pointer-events to pin styles and remove temporary pin when sidebar is closed
=> fix: annotation pin and limits

src/web-components/comments/components/annotation-resolved.ts
=> fix: change 'you resolve' to 'you resolved'

src/common/types/cdn.types.ts, src/components/realtime/index.test.ts, src/components/realtime/index.ts, src/components/realtime/types.ts, src/index.ts, src/web-components/comments/components/annotations.test.ts, src/web-components/comments/components/annotations.ts, src/web-components/comments/components/comment-input.ts
- feat: add event to realtime start/stop
- feat: not publish event when component is not started
- fix: save anything in the position field
=> feat: save anything in position

src/common/styles/global.css, src/components/who-is-online/index.ts, src/core/launcher/index.ts, src/web-components/presence-mouse/index.test.ts, src/web-components/presence-mouse/index.ts, src/web-components/who-is-online/components/dropdown.test.ts, src/web-components/who-is-online/components/dropdown.ts, src/web-components/who-is-online/who-is-online.test.ts, src/web-components/who-is-online/who-is-online.ts
Some things were not working as they should, as they were coded testing in a very specific environment. Some changes were made to fix that aspect of the Who Is Online component.
Also, eslint acted in a lot of places I didn't even touch, so there appears to be more changes than there really are.
=> fix: change small sections of code

src/web-components/comments/components/annotation-item.ts, src/web-components/comments/components/comment-input.ts
=> fix: change reply input placeholder

src/web-components/comments/css/float-button.style.ts
[viciante.webm](https://github.com/SuperViz/sdk/assets/111044527/7d1ce9a2-4dd2-4237-9bab-232f1e05138f)
=> feat: improve animation float button

jest.setup.js, src/components/comments/canvas-pin-adapter/index.test.ts, src/components/comments/canvas-pin-adapter/index.ts, src/components/comments/canvas-pin-adapter/types.ts, src/components/comments/types.ts
https://github.com/SuperViz/sdk/assets/49524331/83dc8511-f359-43dc-9923-76271a670995
=> feat: pin position

src/components/comments/types.ts, src/web-components/comments/components/comment-input.ts, src/web-components/comments/components/comment-item.ts, src/web-components/comments/css/comment-input.style.ts, src/web-components/comments/css/comment-item.style.ts, src/web-components/comments/utils/mention-handler.test.ts, src/web-components/comments/utils/mention-handler.ts
Add mentions feature with ui to comments component
=> Feat: mentions UI

src/components/who-is-online/index.ts, src/web-components/dropdown/index.style.ts, src/web-components/dropdown/index.ts, src/web-components/icon/types.ts, src/web-components/who-is-online/components/dropdown.ts, src/web-components/who-is-online/components/types.ts, src/web-components/who-is-online/css/dropdown.style.ts, src/web-components/who-is-online/css/who-is-online-style.ts, src/web-components/who-is-online/who-is-online.ts
https://www.notion.so/superviz/Presence-Who-is-online-v-2-1e24edac08cd423c9a1d7d00bc6ac655
Depends on #464
=> feat: WIO UI ux review

src/web-components/comments/comments.ts, src/web-components/comments/components/float-button.ts, src/web-components/comments/components/topbar.ts, src/web-components/comments/css/float-button.style.ts
https://www.notion.so/superviz/Comments-Revis-o-v-2-faaa615792c44324bd8e89555e91d8e1
Depends on #464
=> feat: comments UI ux review

src/components/comments/canvas-pin-adapter/index.test.ts, src/components/comments/canvas-pin-adapter/index.ts, src/components/comments/canvas-pin-adapter/types.ts, src/components/comments/index.ts, src/components/comments/types.ts, src/core/launcher/index.ts, src/web-components/comments/components/annotation-item.ts, src/web-components/comments/components/annotation-pin.ts, src/web-components/comments/components/comment-input.test.ts, src/web-components/comments/components/comment-input.ts, src/web-components/comments/css/annotation-item.style.ts, src/web-components/comments/css/annotation-pin.style.ts, src/web-components/comments/css/comment-input.style.ts, src/web-components/comments/css/comment-item.style.ts
- Few tweaks in CSS
- Correctly display user avatar when creating an annotation
- Hide input faster when creating annotation 
- Focus keyboard on input when starting to create annotation
=> feat: comments review

src/common/types/cdn.types.ts, src/components/comments/canvas-pin-adapter/index.ts, src/components/comments/html-pin-adapter/index.test.ts, src/components/comments/html-pin-adapter/index.ts, src/components/comments/html-pin-adapter/types.ts, src/components/comments/types.ts, src/components/index.ts, src/index.ts, src/web-components/comments/css/annotation-pin.style.ts, src/web-components/comments/css/comment-input.style.ts, src/web-components/comments/css/comments.style.ts, src/web-components/comments/css/float-button.style.ts, src/web-components/modal/styles/index.style.ts
https://github.com/SuperViz/sdk/assets/111044527/df167f41-6aa8-40c4-9ef6-6eda76d38a11
=> feat: html pin

src/components/comments/html-pin-adapter/index.ts, src/web-components/comments/components/annotation-pin.ts
=> feat: keep pins position ratio

__mocks__/comments.mock.ts, src/components/comments/index.test.ts, src/components/comments/types.ts, src/web-components/comments/components/comment-input.ts, src/web-components/comments/components/mention-list.ts, src/web-components/comments/utils/autocomplete-handler.ts, src/web-components/comments/utils/mention-handler.ts
Add participant on mentioned input when you type the complete user name
=> feat: add participant on mentioned input digit

src/components/comments/canvas-pin-adapter/index.ts
1 - update comments position;
2 - fix creating first comment - you can't write the first comment ;
=> fix: update comments position and fix creating first comment

src/components/comments/html-pin-adapter/index.test.ts, src/components/comments/html-pin-adapter/index.ts, src/web-components/comments/css/comment-input.style.ts
https://github.com/SuperViz/sdk/assets/111044527/6a4e4efc-076c-4b5e-9890-1675edd5396c
=> feat: html pin svg support

src/web-components/comments/comments.test.ts, src/web-components/comments/components/comment-input.test.ts
Update the tests with mention comments input
=> refactor: write and update the tests

src/common/types/participant.types.ts, src/components/comments/index.ts, src/services/api/index.ts
Change api rest data received from fetch participants by group
=> Refactor:change to data received from fetch participants by group

src/components/who-is-online/index.ts, src/components/who-is-online/types.ts, src/web-components/base/utils/importStyle.ts, src/web-components/dropdown/index.ts, src/web-components/tooltip/index.ts, src/web-components/who-is-online/components/dropdown.test.ts, src/web-components/who-is-online/components/dropdown.ts, src/web-components/who-is-online/css/dropdown.style.ts, src/web-components/who-is-online/css/who-is-online-style.ts, src/web-components/who-is-online/who-is-online.test.ts, src/web-components/who-is-online/who-is-online.ts
=> feat: allow custom styles wio

src/common/types/meeting-colors.types.ts, src/components/presence-mouse/html/index.test.ts, src/components/presence-mouse/html/index.ts, src/services/realtime/ably/index.test.ts, src/services/realtime/ably/index.ts, src/web-components/who-is-online/components/dropdown.test.ts, src/web-components/who-is-online/components/dropdown.ts, src/web-components/who-is-online/css/who-is-online-style.ts, src/web-components/who-is-online/who-is-online.test.ts, src/web-components/who-is-online/who-is-online.ts
- fix: slot assignment
- fix: review color matchers
=> fix: slot assignment

src/common/styles/global.css, src/components/comments/html-pin-adapter/index.test.ts, src/components/comments/html-pin-adapter/index.ts, src/core/index.ts, src/web-components/comments/components/float-button.ts, src/web-components/comments/css/float-button.style.ts
https://www.notion.so/superviz/Comments-Outline-on-elements-when-hovering-61503c171dbd40f2bc400a0c7b6be469
=> feat: comments html pin outline

src/services/realtime/ably/index.test.ts, src/services/realtime/ably/index.ts
- **fix: validade if slot is assigned when is finding my slot**
- **fix: slot assignment**
=> fix: slots assignment

src/common/styles/global.css, src/components/presence-mouse/html/index.test.ts, src/components/presence-mouse/html/index.ts, src/components/realtime/index.ts, src/components/video/index.ts, src/core/launcher/index.ts, src/services/slot/index.test.ts, src/services/slot/index.ts
- **fix: update slot on ably when it's changed on new io**
- **fix: update participant type when starts the video**
=> Participant updates fixes

src/common/types/stores.types.ts, src/common/utils/use-store.ts, src/components/presence-mouse/canvas/index.ts, src/components/presence-mouse/html/index.test.ts, src/components/presence-mouse/html/index.ts, src/components/who-is-online/index.test.ts, src/components/who-is-online/index.ts, src/components/who-is-online/types.ts, src/services/stores/who-is-online/index.ts, src/services/stores/who-is-online/types.ts, src/web-components/comments/comments.test.ts, src/web-components/comments/comments.ts, src/web-components/comments/components/annotation-filter.ts, src/web-components/comments/components/comment-item.test.ts, src/web-components/comments/components/comment-item.ts, src/web-components/comments/components/types.ts, src/web-components/dropdown/index.test.ts, src/web-components/dropdown/index.ts, src/web-components/dropdown/types.ts, src/web-components/tooltip/index.test.ts, src/web-components/tooltip/index.ts, src/web-components/who-is-online/components/dropdown.test.ts, src/web-components/who-is-online/components/dropdown.ts, src/web-components/who-is-online/components/messages.ts, src/web-components/who-is-online/components/types.ts, src/web-components/who-is-online/who-is-online.test.ts, src/web-components/who-is-online/who-is-online.ts
- Move a good chunk of the logic to the src/components/who-is-online section, instead of keeping it in the web-components folder
- Use the Who Is Online Store to coordinate and update data about the component
- General changes to make the code cleaner
=> refactor: who-is-online

src/core/launcher/index.ts
=> fix: any as component type

src/components/realtime/channel.ts
Removing unknown type from realtime callbacks.
=> fix: use RealtimeMessage instead of unknown in the subscribe and unsubscribe

src/components/video/index.ts
Publish go to and follow events to event bus so the gather and follow presence controls work with video + 3d.
=> fix: presence controls video

src/components/realtime/channel.ts, src/components/realtime/index.ts
Add return type to connect method to improve autocomplete and ts types.
=> fix: add return type to connect method

src/components/comments/canvas-pin-adapter/index.ts, src/web-components/comments/components/comment-input.ts, src/web-components/comments/components/mention-list.ts, src/web-components/comments/css/mention-list.style.ts, src/web-components/comments/utils/mention-handler.ts
- Now, clicking on the mentions button does not close the entire input
- Mention list now closes when erasing the @ symbol
- Improved behavior of mention list in general when typing something: closes when it should close, opens when it should open, keeps open if in the middle of typing someone's name, etc
- Mention button only worked if clicking right at the icon in the center. Now, anywhere is fine
- Mention list is no longer hidden in comments bar
=> fix: comment input behavior

src/components/form-elements/index.ts, src/components/who-is-online/index.test.ts, src/components/who-is-online/index.ts
- Form-elements sync event wasn't being published when input value didn't change; publish it
- Sometimes,Who Is Online initial participants list was being initialized with participants with incomplete information; filter it
=> fix: initialize correct list wio

src/components/realtime/channel.ts, src/components/realtime/types.ts
Aguardar mudança da flag `transcriptOff` para `recordingOff`
=> feat: add connectionId to RealtimeMessage type

src/components/video/index.ts
=> fix: enable recording as truthy

.esbuild/config.js
Testing build with target to ES6
=> feat: add target to es6 in the esm config
